apiVersion: v1
kind: Service
metadata:
  name: wordle-api-service
  namespace: {{ namespace }}
spec:
  selector:
    app: wordle-api
    branch: {{ git_branch }}
  ports:
    - name: http4s-port
      port: 8000